apiVersion: apps/v1
kind: Deployment
metadata:
  name: address
spec:
  selector:
    matchLabels:
      app: address
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
      - name: address
        image: vanglix/vaddress
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: addressip
  namespace: default
spec:
  type: NodePort
  selector:
    name: address
  ports:
  - port: 4000
    targetPort: 3000
    nodePort: 30001


